[package]
name = "sim_time"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy-regex = "3.1.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_with = "3.7.0"
thiserror = "1.0.58"
arbitrary = "1.3.2"

[dev-dependencies]
arbtest = "0.3.1"
rand = "0.8.5"
