[package]
name = "field"
version = "0.1.0"
edition = "2021"

[dependencies]
bresenham = "0.1.1"
grid = { version = "0.13.0", features = ["serde"] }
nalgebra = "0.32.5"

[dev-dependencies]
clap = { version = "4.5.4", features = ["derive"] }
image = "0.25.1"
noise = "0.9.0"
rand = "0.8.5"
